apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      run: sample-api
  template:
    metadata:
      labels:
        run: sample-api
    spec:
      containers:
      - image: minji3262/git-argocd:docker-springboot
        name: sample-api
        ports:
        - containerPort: 8080
          protocol: TCP