apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: sample-api